version: 2
jobs:
  build:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/vektah/goparsify
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure --vendor-only
      - run: go test -v ./...
